import { AgentConfig, Tool, ActivityEntry, MemoryItem, ChatMessage, ProcessFlowStep, NodeCategory } from './types';

export const tools: Tool[] = [
    {
        id: 'web-search',
        name: 'Web Search',
        description: 'Search the web for real-time information',
        icon: 'search',
        category: 'Research',
    },
    {
        id: 'news-authenticity',
        name: 'News Detector',
        description: 'Analyze content to aggressively vet if the news is legitimate or fake.',
        icon: 'check-square',
        category: 'Research',
    },
    {
        id: 'summarizer',
        name: 'Summarizer',
        description: 'Summarize long documents and articles',
        icon: 'file-text',
        category: 'Research',
    },
    {
        id: 'gmail',
        name: 'Gmail',
        description: 'Navigate to Gmail and send emails',
        icon: 'mail',
        category: 'Communication',
    },
    {
        id: 'todo-manager',
        name: 'To-Do Manager',
        description: 'Create and manage task lists',
        icon: 'check-square',
        category: 'Productivity',
    },
    {
        id: 'calculator',
        name: 'Calculator',
        description: 'Perform mathematical calculations',
        icon: 'calculator',
        category: 'Utility',
    },
    {
        id: 'code-interpreter',
        name: 'Code Interpreter',
        description: 'Execute and analyze code snippets',
        icon: 'code',
        category: 'Development',
    },
    {
        id: 'shopping',
        name: 'Shopping',
        description: 'Manage shopping preferences and details',
        icon: 'shopping-cart',
        category: 'Lifestyle',
    },
];

export const defaultAgents: AgentConfig[] = [
    {
        id: 'agent-router',
        name: 'Detect User Intention',
        role: 'Router',
        personality: 'Analytical and precise',
        model: 'gemini-flash-latest',
        modelIcon: 'gemini',
        tools: [],
        memoryEnabled: true,
        memoryType: 'All Messages',
        messages: [],
        knowledgeSources: [],
        inputMessage: '',
        responseFormat: 'Use Markdown',
    },
    {
        id: 'agent-technical',
        name: 'Technical Agent',
        role: 'Technical Support',
        personality: 'Helpful and knowledgeable',
        model: 'gemini-flash-latest',
        modelIcon: 'gemini',
        tools: ['web-search', 'code-interpreter'],
        memoryEnabled: true,
        memoryType: 'All Messages',
        messages: [],
        knowledgeSources: [],
        inputMessage: '',
        responseFormat: 'Use Markdown',
    },
    {
        id: 'agent-sales',
        name: 'Sales Agent',
        role: 'Sales Representative',
        personality: 'Friendly and persuasive',
        model: 'gemini-flash-latest',
        modelIcon: 'gemini',
        tools: ['web-search', 'gmail'],
        memoryEnabled: true,
        memoryType: 'All Messages',
        messages: [],
        knowledgeSources: [],
        inputMessage: '',
        responseFormat: 'Use Markdown',
    },
    {
        id: 'agent-2',
        name: 'Agent 2',
        role: 'General Assistant',
        personality: 'Versatile and adaptable',
        model: 'gemini-flash-latest',
        modelIcon: 'gemini',
        tools: ['summarizer', 'todo-manager'],
        memoryEnabled: false,
        memoryType: 'All Messages',
        messages: [],
        knowledgeSources: [],
        inputMessage: '',
        responseFormat: 'Use Markdown',
    },
];

export const sampleActivityLog: ActivityEntry[] = [
    {
        id: 'act-1',
        agentId: 'agent-router',
        agentName: 'Detect User Intention',
        type: 'thinking',
        content: 'Analyzing user message to determine intent classification...',
        timestamp: new Date(Date.now() - 60000),
        status: 'completed',
    },
    {
        id: 'act-2',
        agentId: 'agent-router',
        agentName: 'Detect User Intention',
        type: 'action',
        content: 'Classified intent as: Technical Support Query',
        timestamp: new Date(Date.now() - 55000),
        status: 'completed',
    },
    {
        id: 'act-3',
        agentId: 'agent-router',
        agentName: 'Detect User Intention',
        type: 'output',
        content: 'Routing to Technical Agent via output port 0',
        timestamp: new Date(Date.now() - 50000),
        status: 'completed',
    },
    {
        id: 'act-4',
        agentId: 'agent-technical',
        agentName: 'Technical Agent',
        type: 'thinking',
        content: 'Received technical support query. Analyzing the error logs provided...',
        timestamp: new Date(Date.now() - 45000),
        status: 'completed',
    },
    {
        id: 'act-5',
        agentId: 'agent-technical',
        agentName: 'Technical Agent',
        type: 'tool_use',
        content: 'Using Web Search to look up error code: ERR_CONNECTION_REFUSED',
        timestamp: new Date(Date.now() - 40000),
        status: 'completed',
    },
    {
        id: 'act-6',
        agentId: 'agent-technical',
        agentName: 'Technical Agent',
        type: 'output',
        content: 'I\'ve reviewed the provided error logs. It appears you\'re encountering several different issues, and I\'ll break them down with potential solutions...',
        timestamp: new Date(Date.now() - 30000),
        status: 'completed',
    },
];

export const sampleMemory: MemoryItem[] = [
    {
        id: 'mem-1',
        agentId: 'agent-technical',
        type: 'context',
        content: 'User is working on a Flowise instance with server configuration issues.',
        timestamp: new Date(Date.now() - 120000),
    },
    {
        id: 'mem-2',
        agentId: 'agent-technical',
        type: 'task',
        content: 'Resolved: Server error log analysis - identified 3 critical issues',
        timestamp: new Date(Date.now() - 300000),
    },
    {
        id: 'mem-3',
        agentId: 'agent-sales',
        type: 'preference',
        content: 'User prefers concise, actionable responses with code examples.',
        timestamp: new Date(Date.now() - 600000),
    },
    {
        id: 'mem-4',
        agentId: 'agent-router',
        type: 'task',
        content: 'Completed: Intent classification for 15 user messages with 94% accuracy',
        timestamp: new Date(Date.now() - 900000),
    },
];

export const sampleChat: ChatMessage[] = [
    {
        id: 'chat-1',
        role: 'assistant',
        content: 'Hello! How can I assist you today?',
        timestamp: new Date(Date.now() - 120000),
    },
    {
        id: 'chat-2',
        role: 'user',
        content: 'can you help me with this error?',
        timestamp: new Date(Date.now() - 90000),
        attachments: ['server-error.log'],
    },
    {
        id: 'chat-3',
        role: 'assistant',
        content: 'Okay, I\'ve reviewed the provided error logs from your Flowise instance. It appears you\'re encountering several different issues, and I\'ll break them down and provide potential solutions:\n\n**1.** `2024-05-24 14:30:27 [ERROR] [server]: Error: Error`',
        timestamp: new Date(Date.now() - 30000),
    },
];

export const processFlow: ProcessFlowStep[] = [
    {
        id: 'pf-1',
        name: 'Start',
        icon: 'play',
        status: 'completed',
    },
    {
        id: 'pf-2',
        name: 'Detect User Intention',
        icon: 'route',
        status: 'completed',
    },
];

export const nodeCategories: NodeCategory[] = [
    {
        name: 'Agent Flows',
        items: [
            {
                id: 'nc-start',
                name: 'Start',
                description: 'The starting point of the flow',
                icon: 'play',
                type: 'start',
            },
            {
                id: 'nc-agent',
                name: 'Agent',
                description: 'Dynamically choose and utilize tools during runtime, enabling multi-step reasoning',
                icon: 'bot',
                type: 'agent',
            },
            {
                id: 'nc-http',
                name: 'HTTP',
                description: 'Send an HTTP request',
                icon: 'globe',
                type: 'http',
            },
            {
                id: 'nc-model',
                name: 'Chat Model',
                description: 'Connect to an AI model provider',
                icon: 'bot',
                type: 'model',
            },
            {
                id: 'nc-memory',
                name: 'Simple Memory',
                description: 'Stores in db, so no credentials required',
                icon: 'database',
                type: 'memory',
            },
            {
                id: 'nc-sticky-note',
                name: 'Sticky Note',
                description: 'Add notes to the agent flow',
                icon: 'sticky-note',
                type: 'sticky',
            },
        ],
    },
    {
        name: 'Tools',
        items: tools.map(t => ({
            id: `nc-tool-${t.id}`,
            name: t.name,
            description: t.description,
            icon: t.icon,
            type: 'tool'
        })),
    },
];
